package mygame;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Todd
 */
public class padData extends javax.swing.JFrame {

    /**
     * Creates new form padData
     */
    public padData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        padPanel = new javax.swing.JPanel();
        updatePADBtn = new javax.swing.JButton();
        pLbl = new javax.swing.JLabel();
        aLbl = new javax.swing.JLabel();
        dLbl = new javax.swing.JLabel();
        pTF = new javax.swing.JTextField();
        aTF = new javax.swing.JTextField();
        dTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        padPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("PAD Values"));
        padPanel.setName(""); // NOI18N

        updatePADBtn.setText("Send PAD Values");
        updatePADBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatePADBtnMouseClicked(evt);
            }
        });

        pLbl.setText("Pressure:");

        aLbl.setText("Arousal:");

        dLbl.setText("Dominance:");

        pTF.setText("0");

        aTF.setText("0");

        dTF.setText("0");

        javax.swing.GroupLayout padPanelLayout = new javax.swing.GroupLayout(padPanel);
        padPanel.setLayout(padPanelLayout);
        padPanelLayout.setHorizontalGroup(
            padPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(padPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(padPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatePADBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addGroup(padPanelLayout.createSequentialGroup()
                        .addComponent(pLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pTF))
                    .addGroup(padPanelLayout.createSequentialGroup()
                        .addComponent(dLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dTF))
                    .addGroup(padPanelLayout.createSequentialGroup()
                        .addComponent(aLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aTF)))
                .addContainerGap())
        );
        padPanelLayout.setVerticalGroup(
            padPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, padPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(padPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pLbl)
                    .addComponent(pTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(padPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aLbl)
                    .addComponent(aTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(padPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLbl)
                    .addComponent(dTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updatePADBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(padPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(padPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatePADBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePADBtnMouseClicked

        Socket mySocket = null;
        String hostName = "localhost";
        int portNumber = 5555;
        DataOutputStream os = null;
        
        try {
            mySocket = new Socket(hostName, portNumber);
            mySocket.setSoTimeout(50);
            os = new DataOutputStream(mySocket.getOutputStream());

        } catch (Exception e) {
           // System.err.println("Exception:  " + e);
        }

        if (mySocket!= null && os != null) {
            try {
                // The capital string before each colon has a special meaning to SMTP
                // you may want to read the SMTP specification, RFC1822/3
                os.writeDouble(Double.parseDouble(pTF.getText()));
                os.writeDouble(Double.parseDouble(aTF.getText()));
                os.writeDouble(Double.parseDouble(dTF.getText()));

                os.close();
                mySocket.close();

            } catch (UnknownHostException e) {
               // System.err.println("Trying to connect to unknown host: " + e);
            } catch (IOException e) {
              //  System.err.println("IOException:  " + e);
            }
        }
    }//GEN-LAST:event_updatePADBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(padData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(padData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(padData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(padData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new padData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLbl;
    private javax.swing.JTextField aTF;
    private javax.swing.JLabel dLbl;
    private javax.swing.JTextField dTF;
    private javax.swing.JLabel pLbl;
    private javax.swing.JTextField pTF;
    private javax.swing.JPanel padPanel;
    private javax.swing.JButton updatePADBtn;
    // End of variables declaration//GEN-END:variables
}
